/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 title_text_v3.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from 'framer-motion-3d'


export function TextModel(props) {

    

    // sheck the screen to set the scale
    const scale = !props.isMobile? 1.5 :  0.7
    const position = !props.isMobile ? [-3.531, 1.6, 0] :  [-1.5, 3, 0]
    const { nodes, materials } = useGLTF('/title_text_v3.gltf')
    return (
        <motion.group 
        initial={{ y: -0.5 }}
        animate={{ y: -0.2 }}
        transition={{
            repeat: Infinity,
            repeatType: "reverse",
            duration: 1,
            ease: "easeInOut",
        }}
        {...props} dispose={null}>
            <mesh scale={scale} geometry={nodes.Unrevealed_XO.geometry} material={materials.text_color} position={position} rotation={[Math.PI / 1.76, 0, 0]} />
        </motion.group>
    )
}

useGLTF.preload('/title_text_v3.gltf')


