/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tictactoee.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from 'framer-motion-3d'

export function TicTacToeeModel(props) {
    const { nodes, materials } = useGLTF('/tictactoee.gltf')
    const position = props.isMobile ? [0.003, 1.39, 0.038] : [4.403, 1.89, 0.038]
    // const scale = props.isMobile ? 0.5 : 1.5
    return (
        <motion.group 
        whileHover={{ rotateY: 31.5 }}
        
        {...props} dispose={null}  rotation={[Math.PI / 2, 0, 0]} position={position}>
            <mesh geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[0.003, -0.09, 0.038]} rotation={[Math.PI / 2, 0, 0]} scale={[0.686, 0.686, 0.031]} />
            <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[0.003, -0.021, 0.042]} scale={[0.153, 0.038, 0.153]} />
            <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[-0.467, -0.022, 0.038]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={[0.189, 0.038, 0.038]} />
            <mesh geometry={nodes.Cube002.geometry} material={materials['Material.003']} position={[0.472, -0.022, 0.503]} rotation={[Math.PI / 2, 0, 1.248]} scale={[0.189, 0.038, 0.038]} />
            <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[0.468, -0.021, -0.423]} scale={[0.153, 0.038, 0.153]} />
            <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} position={[-0.459, -0.021, 0.491]} scale={[0.153, 0.038, 0.153]} />
            <mesh geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[-0.031, -0.054, -0.754]} rotation={[-1.878, 0, Math.PI / 4]} scale={[0.189, 0.038, 0.038]} />
            <mesh geometry={nodes.Curve.geometry} material={materials.SVGMat} position={[0.009, -0.058, 0.042]} scale={0.631} />
        </motion.group>
    )
}

useGLTF.preload('/tictactoee.gltf')
